name: piper_phonemize
description: >
  Dart and Flutter bindings for piper-phonemize, a fast phonemization library
  backed by espeak-ng. Converts text to phoneme code points for use with
  text-to-speech systems.
version: 1.3.1
homepage: https://github.com/csukuangfj/piper-phonemize
repository: https://github.com/csukuangfj/piper-phonemize
license: GPL-3.0

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  path: ^1.9.0
  path_provider: ^2.1.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true

  assets:
    - espeak-ng-data/
