name: npm-addon-linux-x64

on:
  push:
    branches:
      - node-addon
  workflow_dispatch:

concurrency:
  group: npm-addon-linux-x64-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  npm-addon-linux-x64:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Display node version
        shell: bash
        run: |
          node --version

      - name: Build piper-phonemize
        shell: bash
        run: |
          docker run --rm \
            --volume ${{ github.workspace }}/:/shared/ \
            quay.io/pypa/manylinux2014_x86_64 \
            bash -c '
              uname -a
              gcc --version
              cmake --version
              cd /shared

              mkdir build
              cd build
              cmake \
                -DCMAKE_INSTALL_PREFIX=./install \
                -DBUILD_SHARED_LIBS=ON \
                -DBUILD_PIPER_PHONEMIZE_PYTHON=OFF \
                -DBUILD_PIPER_PHONEMIZE_CORE_TESTS=OFF \
                ..
              make -j$(nproc) install
            '

      - name: Build piper-phonemize node-addon
        shell: bash
        run: |
          d=$PWD
          export PIPER_PHONEMIZE_INSTALL_DIR=$d/build/install

          cd scripts/node-addon-api
          npm install cmake-js@7.3.0 node-addon-api@8.0.0
          ./run.sh

      - name: Package
        shell: bash
        run: |
          bash .github/scripts/node-addon/run.sh

          # Copy shared libraries from build
          cp -fv build/install/lib/libpiper_phonemize_core.so piper-phonemize-linux-x64/
          rm -fv piper-phonemize-linux-x64/*cxx*

          ls -lh piper-phonemize-linux-x64/

      - name: Pack
        shell: bash
        run: |
          cd piper-phonemize-linux-x64
          npm pack
          mv *.tgz ../

      - name: Display tgz contents
        shell: bash
        run: |
          ls -lh ./*.tgz
          echo "--- Contents of tgz ---"
          tar tvf ./*.tgz

      - uses: actions/upload-artifact@v4
        with:
          name: piper-phonemize-linux-x64
          path: ./*.tgz

      - name: Publish to npm
        shell: bash
        run: |
          cd piper-phonemize-linux-x64
          npm publish --provenance --access public

      - name: Setup tmate session
        if: false
        # if: failure()
        uses: mxschmitt/action-tmate@v3
