name: swift

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: swift-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build macOS xcframework
        run: ./build-swift-macos.sh

      - name: Build iOS xcframework
        run: ./build-ios.sh

      - name: Download espeak-ng-data
        run: |
          curl -OL https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/espeak-ng-data.tar.bz2
          tar xvf espeak-ng-data.tar.bz2
          rm -f espeak-ng-data.tar.bz2

      - name: Test swift-api-examples
        run: |
          cd swift-api-examples
          bash run.sh

      - name: Test spm-examples
        run: |
          cd spm-examples
          bash run.sh
