name: test

on:
  push:
    branches:
      - wheels-for-sherpa-onnx

    tags:
      - '*'
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13, ubuntu-22.04-arm, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install piper-phonemize
        shell: bash
        run: |
          python3 -m pip install piper_phonemize -f https://k2-fsa.github.io/icefall/piper_phonemize.html

      - name: Show
        shell: bash
        run: |
          rm -rf piper_phonemize
          python3 -c "import piper_phonemize; print(piper_phonemize.__file__)"

      - name: Test piper-phonemize
        shell: bash
        run: |
          python3 -c "from piper_phonemize import phonemize_espeak; tokens_list = phonemize_espeak('how are you doing', 'en-us'); print(tokens_list)"
