name: test-dot-net

on:
  push:
    branches:
      - master
      - dot-net
  workflow_dispatch:

concurrency:
  group: test-dot-net-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: ubuntu-22.04-arm
            rid: linux-arm64
          - os: macos-latest
            rid: osx-arm64
          - os: macos-15-intel
            rid: osx-x64
          - os: windows-2022
            rid: win-x64
          - os: windows-11-arm
            rid: win-arm64
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run example
        shell: bash
        run: |
          cd dotnet-examples/PhonemizeText
          dotnet run
