name: test-go-package

on:
  push:
    branches:
      - go-api
  workflow_dispatch:

jobs:
  test-go-package-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download espeak-ng-data
        run: |
          curl -OL https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/espeak-ng-data.tar.bz2
          tar xvf espeak-ng-data.tar.bz2

      - name: Test released Go package
        run: |
          cd go-api-examples
          go mod tidy
          go run main.go $GITHUB_WORKSPACE/espeak-ng-data

  test-go-package-linux-arm64:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download espeak-ng-data
        run: |
          curl -OL https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/espeak-ng-data.tar.bz2
          tar xvf espeak-ng-data.tar.bz2

      - name: Test released Go package
        run: |
          cd go-api-examples
          go mod tidy
          go run main.go $GITHUB_WORKSPACE/espeak-ng-data

  test-go-package-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download espeak-ng-data
        run: |
          curl -OL https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/espeak-ng-data.tar.bz2
          tar xvf espeak-ng-data.tar.bz2

      - name: Test released Go package
        run: |
          cd go-api-examples
          go mod tidy
          go run main.go $GITHUB_WORKSPACE/espeak-ng-data

  test-go-package-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download espeak-ng-data
        run: |
          curl -OL https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/espeak-ng-data.tar.bz2
          tar xvf espeak-ng-data.tar.bz2

      - name: Test released Go package
        shell: bash
        run: |
          cd go-api-examples
          go mod tidy
          # On Windows, DLLs must be in PATH. The Go module cache has them.
          DLL_DIR=$(go env GOMODCACHE)/github.com/csukuangfj/piper-phonemize-go-windows@v1.4.1/lib/x86_64-pc-windows-gnu
          export PATH="$DLL_DIR:$PATH"
          go run main.go $GITHUB_WORKSPACE/espeak-ng-data
